const List<String> aiTipsList = [
  "Break big tasks into smaller steps.",
  "Revise before sleeping for better memory retention.",
  "Use the Pomodoro technique for focused sessions.",
  "Teach others to understand better.",
  "Keep your phone away while studying.",
  "Use active recall instead of passive reading.",
  "Make concept maps to connect ideas.",
  "Visualize tough concepts.",
  "Quiz yourself after every topic.",
  "Mix different subjects in your day.",
  "Use spaced repetition for long-term memory.",
  "Highlight only key points, not entire paragraphs.",
  "Take short breaks every 25–30 minutes.",
  "Summarize what you studied in your own words.",
  "Avoid multitasking while studying.",
  "Sleep at least 7 hours to boost brain power.",
  "Study at the same time daily to build a habit.",
  "Practice writing what you learn.",
  "Use past exam papers to prepare.",
  "Start with hard subjects when you're fresh.",
  "Write summaries after each session.",
  "Record yourself explaining a topic and play it back.",
  "Break chapters into manageable sections.",
  "Create a dedicated study space.",
  "Set specific, measurable goals for each session.",
  "Use a timer to manage study blocks.",
  "Use color-coded notes to organize information.",
  "Listen to instrumental music for better concentration.",
  "Avoid studying on your bed to stay alert.",
  "Join study groups for collaborative learning.",
  "Set daily study goals and track them.",
  "Reward yourself after completing tasks.",
  "Use apps to block distracting websites.",
  "Study with flashcards for quick reviews.",
  "Read aloud to reinforce memory.",
  "Turn headings into questions and answer them.",
  "Track your progress in a study journal.",
  "Use real-world examples to understand abstract concepts.",
  "Explain difficult topics to a friend or a pet.",
  "Use dual coding: combine text with visuals.",
  "Create acronyms or mnemonics to remember facts.",
  "Revisit tough topics weekly.",
  "Organize notes after each class.",
  "Limit caffeine intake before bed.",
  "Watch educational videos on the topic.",
  "Practice teaching a lesson plan.",
  "Use sticky notes for quick facts.",
  "Organize study material by theme.",
  "Focus on understanding, not memorizing.",
  "Practice solving problems regularly.",
  "Change study locations occasionally.",
  "Reflect on what study method works best for you.",
  "Stay hydrated during study sessions.",
  "Keep a 'parking lot' for distracting thoughts.",
  "Use bullet points in notes for clarity.",
  "Compare different sources for deeper understanding.",
  "Avoid perfectionism — aim for progress.",
  "Use the Feynman technique to simplify concepts.",
  "Limit social media during study hours.",
  "Sleep with a consistent schedule.",
  "Start your day with light review.",
  "Teach a concept in 60 seconds to simplify it.",
  "Use diagrams or infographics to revise.",
  "Label diagrams from memory.",
  "Break long sessions with physical movement.",
  "Revise with a partner and quiz each other.",
  "Use practice apps for quick tests.",
  "Plan your weekly study in advance.",
  "Create a checklist of what to cover.",
  "Use voice notes to record quick thoughts.",
  "Have a ‘doubt journal’ for questions to resolve.",
  "Track habits with a study calendar.",
  "Meditate to improve focus before study.",
  "Repeat aloud what you want to memorize.",
  "Watch summary videos for fast review.",
  "Revise notes on the same day they’re taken.",
  "Set a weekly review day.",
  "Plan study sessions around your energy levels.",
  "Avoid comparing your pace with others.",
  "Use analogies to relate new info to old.",
  "Keep a tidy study desk.",
  "Use a whiteboard to sketch ideas.",
  "Read summaries before diving deep.",
  "Use digital flashcards like Anki or Quizlet.",
  "Start with a warm-up review activity.",
  "Use mind maps for brainstorming.",
  "Keep motivation quotes on your desk.",
  "Celebrate small study milestones.",
  "Read backwards from summaries to details.",
  "Prioritize understanding over speed.",
  "Create mock exams to simulate pressure.",
  "Use red/green markers for confident vs. weak areas.",
  "Review your mistakes weekly.",
  "Use learning objectives to stay on track.",
  "Switch between active and passive tasks.",
  "Rest your eyes with the 20-20-20 rule.",
  "Don’t study hungry or overfull.",
  "Create a reward jar for study hours.",
  "Link study topics with real-world events.",
  "Use sound cues to start or end sessions.",
  "Schedule downtime to prevent burnout.",
  "Read questions before reading chapters.",
  "Summarize paragraphs in margins.",
  "Use the Cornell Note-taking system.",
  "Create a study playlist.",
  "Avoid late-night cramming.",
  "Write down distractions to revisit later.",
  "Use spaced quiz apps.",
  "Mark tough questions for second review.",
  "Review mistakes with curiosity, not judgment.",
  "Keep tech tools updated for efficiency.",
  "Match your study method to the subject type.",
  "Use call-and-response with a friend.",
  "Create fill-in-the-blank sheets.",
  "Make topic summaries by week.",
  "Keep sessions short when tired.",
  "Make mind maps from memory.",
  "Use ‘teach-back’ as your daily review method.",
  "Drink water before you study.",
  "Match tasks with your mental energy.",
  "Have a consistent pre-study routine.",
  "Warm up with something you enjoy.",
  "Use different fonts/colors to encode memories.",
  "Avoid background TV or loud chatter.",
  "Study using both written and digital notes.",
  "Take photos of board/notes when possible.",
  "Set a “why” for each subject.",
  "Use metaphors to remember tough ideas.",
  "Watch documentaries on your subject.",
  "Ask teachers for additional resources.",
  "Keep track of common mistakes.",
  "Review right after class.",
  "Label difficult concepts as “still learning” instead of “bad at this.”",
  "Use silent study marathons with friends.",
  "Pick a study buddy with similar goals.",
  "Keep your goals visible while studying.",
  "Visualize your success to boost motivation.",
  "Reward yourself with breaks, not distractions.",
  "Use timers to challenge yourself to finish small tasks.",
  "Rotate between subjects to prevent boredom.",
  "Use “5 more minutes” technique to extend focus.",
  "Delete distracting apps before exams.",
  "Be kind to yourself during tough days.",
  "Create summary posters for wall reminders.",
  "Practice verbalizing key points in under a minute.",
  "Find your most alert hours and use them.",
  "Make a 30-day study challenge calendar.",
  "Scan notes with your phone for quick reference.",
  "Color-code subjects in your planner.",
  "Make flashcards for definitions and formulas.",
  "Have a dedicated exam-prep notebook.",
  "Group similar topics when reviewing.",
  "Make visual timelines for history or events.",
  "Add emojis or sketches to notes for memory aid.",
  "Use break times to stretch or walk.",
  "Turn off notifications during study hours.",
  "Designate “phone breaks” rather than casual use.",
  "Make your own study guides.",
  "Use YouTube playlists for focused learning.",
  "Schedule review marathons with friends.",
  "Combine reading and listening for dual input.",
  "Say concepts differently to test comprehension.",
  "Make “why” and “how” questions a habit.",
  "Study in natural light when possible.",
  "Keep a list of achievements to stay motivated.",
  "Follow a “learn, test, explain” cycle.",
  "Create animations or doodles of complex topics.",
  "Write goals at the top of each notebook page.",
  "Say out loud: “This is how I remember it…”",
  "Find your optimal noise level: silence, white noise, or music.",
  "Create and stick to an exam countdown schedule.",
  "Review what didn’t work last time and adapt.",
  "Avoid back-to-back long sessions without breaks.",
  "Track what resources help you most.",
  "Keep old notes for quick revision boosts.",
  "Make a checklist for every subject unit.",
  "Use “before and after” charts to track learning.",
  "Imagine explaining a topic to a 5-year-old.",
  "Use review games like Kahoot with friends.",
  "Make tough topics fun with analogies.",
  "Balance study with hobbies to avoid burnout.",
  "Journal how you feel after studying.",
  "Break reading into digestible chunks.",
  "Use post-study reflections to improve.",
  "Don’t fear re-learning; it strengthens memory.",
  "Say: “I’m learning this,” instead of “I can’t do this.”",
  "Prepare materials the night before study days.",
  "Actively monitor your focus level.",
  "Study to understand, not just to pass.",
  "You’re not behind — you’re building your path.",
];
